spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcm?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true # 'fcm' ??? MySQL RDB? ????? ?????.
    username: root
    password: choi1209 # ???? MySQL ????? ????? ???.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # 'create'? ?????? ?? ? DDL? ?????.
    show-sql: true # SQL ??? ??? ?????.
    properties:
      hibernate:
        format_sql: true # SQL? ?? ?? ?????.
        use_sql_comments: true # SQL? ??? ?????.

  logging:
    level:
      org:
        hibernate:
          SQL: debug # SQL ?? ?? ??? ???? ?????.
          type:
            descriptor:
              sql:
                BasicBinder: trace # SQL ??? ????? ?????.
